[package]
name = "cobra"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
sexp = "1.1.4"
dynasm = "2.0.0"
dynasmrt = "2.0.0"
im = "15"

[dev-dependencies]
prettydiff = "0.6.4"
lazy_static = "1.4.0"